= Site Reliability Engineering

:toc: auto


== Introduction
This document tries to explain the main ideas of Site Reliablity Engineering in a short way.

== The traditional Sysadmin Approach to Service Management

Historically, companies have employed systems administrators to run complex computing systems.
Because the sysadmin role requires a markedly different
skill set than that required of a product’s developers, developers and sysadmins are
divided into discrete teams: “development” and “operations” or “ops.”

The sysadmin approach and the accompanying development/ops split has a number of disadvantages and pitfalls. These fall broadly into two categories: direct costs and indirect costs.

Direct costs are neither subtle nor ambiguous. Running a service with a team that relies on manual intervention for both change management and event handling becomes expensive as the service and/or traffic to the service grows, because the size of the team necessarily scales with the load generated by the system.

The indirect costs of the development/ops split can be subtle, but are often more expensive to the organization than the direct costs. These costs arise from the fact that the two teams are quite different in background, skill set, and incentives. They
use different vocabulary to describe situations; they carry different assumptions about both risk and possibilities for technical solutions; they have different assumptions about the target level of product stability. The split between the groups can easily
become one of not just incentives, but also communication, goals, and eventually, trust and respect. This outcome is a pathology.


== DevOps or SRE ?

The term “DevOps” emerged in industry in late 2008 and is still in a state of flux. 
Its core principles—involvement of the IT function in
each phase of a system’s design and development, heavy reliance on automation versus human effort, the application of engineering practices and tools to operations tasks—are consistent with many of SRE’s principles and practices. 

From an Atos point of view DevOps consists of

* Agile
* Standardization
* Automatization
* Colaboration


You could view DevOps as a generalization of several core SRE principles to a wider range of organizations, management structures, and personnel. One could equivalently view SRE as a
specific implementation of DevOps with some idiosyncratic extensions.


== SRE Teams

The result of Googles approach to hiring for SRE is that they end up with a team of people
who 
(a) will quickly become bored by performing tasks by hand, and 
(b) have the skill set necessary to write software to replace their previously manual work, even
when the solution is complicated. 

SREs also end up sharing academic and intellectual background with the rest of the development organization. 
Therefore, SRE is fundamentally doing work that has historically been done by an operations team, but using engineers with software expertise, and banking on the fact that these engineers are
inherently both predisposed to, and have the ability to, design and implement automation with software to replace human labor.

By design, it is crucial that SRE teams are focused on engineering. Without constant engineering, operations load increases and teams will need more people just to keep pace with the workload.

Eventually, a traditional ops-focused group scales linearly
with service size: if the products supported by the service succeed, the operational load will grow with traffic. That means hiring more people to do the same tasks over and over again.

To avoid this fate, the team tasked with managing a service needs to code or it will drown. Therefore, Google places a 50% cap on the aggregate “ops” work for all SREs tickets, on-call, manual tasks, etc. 

This cap ensures that the SRE team has enough time in their schedule to make the service stable and operable. This cap is an upper
bound; over time, left to their own devices, the SRE team should end up with very little operational load and almost entirely engage in development tasks, because the
service basically runs and repairs itself: we want systems that are automatic, not just automated. In practice, scale and new features keep SREs on their toes.


In general, an SRE team is responsible for

* availability
* latency
* performance
* efficiency
* change management
* monitoring,
* emergency response
* capacity planning 

of their service(s).


== Core principles of SRE 
[Attributes]
|===
|Principle |Description |How to apply

|Focus on engineering
|Prefer automation ofer manual tasks
|Only 50% reserved for Ops Tasks 

|Maximum Change Velocity Without Violating SLO's
|Zero Downtime is not a achievable goal
|Accept Outages as normal. Deal with the error budget and us it to increase velocity

|Monitoring
|Monitoring should
never require a human to interpret any part of the alerting domain. Instead, software
should do the interpreting, and humans should be notified only when they need to
take action.
a|Differ output in 

* Alerts (urgent, inform immediately)
* Tickets (planable, inform, but note immediately)
* Logging ( recorded, just for investigations )

Avoid noise

|Emergency Response
|Cell 2, row 1
|Cell 3, row 1

|Change Management
|Cell 2, row 1
|Cell 3, row 1

|Provisioning
|Cell 2, row 1
|Cell 3, row 1

|Efficiency and Performance
|Cell 2, row 1
|Cell 3, row 1

|===



== Sources

[Attributes]
|===
|Title | Reference 

|Site Reliability Engineering
|http://oreilly.com/catalog/errata.csp?isbn=9781491929124 f

|===

